version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=menu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/menu
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  dbdata:
    driver: local